# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kate's Programming Journey
email: kateschoene@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Began school at Austin Coding Academy as a means of becoming a full-stack developer on July 25, 2016. Whoop! Whoop! This is documentation of that journey. 
baseurl: "kathrynjschoenen/aca-blog" # the subpath of your site, e.g. /blog
url: "http://kathrynjschoenen.com" # the base hostname & protocol for your site
twitter_username: chrysalisatx
github_username:  kateschoene

# Build settings
markdown: kramdown
